const Degrees=[
    "Bachelor",
    "Master",
    "Phd",
    "Other"
  ];

const Religions=[
        "Christianisme",
        "Islam",
        "Judaïsme",
        "Bouddhisme",
        "Hindouisme",
        "Sikhisme",
        "Autre"
      ];

const Origins=[
  "Caucasien",
   "Moyen orient",
   "noir/africain",
   "Asiatique",
   "Sud asiatique",
   "Latino/hispanique",
   "Mixte",
   "Amazigh"
];

const Interests = [
    'James Corbett',
    'dragonflight',
    'naruto',
    'festivals',
    'One night',
    'formules chimiques',
    'inventer des choses',
    'réparer des appareils',
    'uchiwa madara',
    'hiver',
    'cinéma',
    'Dessiner',
    'Diriger et organiser',
    'Écrire',
    'lire',
    'Être leader',
    'Sasuke Uchiwa',
    'Afrique',
    'événements historiques',
    'boruto',
    'été',
    'Étudier des êtres vivants',
    'administrer',
    'voyages',
    'luffy',
    'musées',
    'overwatch 2',
    'camping',
    'rinnegan',
    'Aider les gens',
    'vin',
    'fifa 23',
    'chasse',
    'plages',
    'pêche',
    'rencontres',
    'Itachi Uchiwa',
    'concret',
    'snapchat',
    'statistiques',
    'Roronoa zoro',
    'neige',
    'musique',
    'rasengan',
    'séries',
    'cartes géographiques',
    'films',
    'thé',
    'Kakashi Hatake',
    'œuvres littéraires',
    'appareils électroniques',
    'hinata hyuga',
    'mathématique',
    'les sorties',
    'Peindre',
    'nasa',
    'Jiraya',
    'netflix',
    'dessiner',
    'sculpter',
    'otsutsuki momoshiki',
    'Penser, raisonner',
    'sport',
    'Cuisine',
    'Olives',
    'Gaï Maito',
    'Klaus Schwab',
    'animaux',
    'travail minutieux',
    'Se promener',
    'connaissances',
    'beaute',
    'kurama',
    'ordinateurs',
    'photocopieurs',
    'télécopieurs',
    'laboratoire',
    'youtube',
    'échanges avec les autres',
    'otsutsuki isshiki',
    'Compétition',
    'relativité',
    'Esthétique',
    'nature',
    'Influence',
    'mensonge corona',
    'bière',
    'tiktok',
    'Prendre des risques',
    'minecraft',
    'sciences',
    'kawaki',
    'whisky',
    'Huile d’olive',
    'Love is blind',
    'cartel pharmaceutique',
    'restaurants',
    'facebook',
    'complots',
    'mécanique quantique',
    'café',
  ];

  module.exports = {Degrees,Religions,Origins,Interests};
